spring:
  application:
    name: sample
  main:
    lazy-initialization: true
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    username: sample
    password: sample
    hikari:
      auto-commit: true
      pool-name: ${spring.application.name}
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      data-source-properties:
        allowPublicKeyRetrieval: true
        serverTimezone: UTC
        useSSL: false
  jpa:
    database: mysql
    database-platform: MYSQL
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: "org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy"
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:/db.changelog-master.yml
    url: jdbc:mysql://localhost:3306/sample?serverTimezone=UTC&useSSL=false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jooq:
    sql-dialect: MYSQL
logging:
  level:
    org:
      jooq: debug
